// Copyright © 2026 Alex Navarro

import type { PlanetBlueprint } from './types'
import type { TerrainFaceResult } from './terrainFace'

// Core
import { BufferAttribute, BufferGeometry } from 'three'
import { mergeVertices } from 'three/addons/utils/BufferGeometryUtils.js'

// Utility
import { FACE_DIRECTIONS } from './terrainFace'
import { getTerrainWorkerPool } from './workerPool'

export type PlanetGeometry = {
  geometry: BufferGeometry
  minElevation: number
  maxElevation: number
}

/**
 * Builds a world's surface as one welded, indexed geometry.
 *
 * Six faces are generated by the shared worker pool, concatenated, and welded at their shared edges before
 * normals are computed once for the whole sphere. Computing normals per face leaves visible seams along every
 * cube edge.
 */
export async function buildPlanetGeometry(
  blueprint: Pick<PlanetBlueprint, 'seed' | 'type' | 'palette' | 'terrain'>,
  resolution: number,
  radius: number,
): Promise<PlanetGeometry> {
  const pool = getTerrainWorkerPool()
  const faces = await Promise.all(
    FACE_DIRECTIONS.map((direction) => pool.runFace({
      seed: blueprint.seed,
      type: blueprint.type,
      palette: blueprint.palette,
      terrain: blueprint.terrain,
      resolution,
      radius,
      direction,
    })),
  )
  return assembleFaces(faces)
}

function assembleFaces(faces: TerrainFaceResult[]): PlanetGeometry {
  let vertexTotal = 0
  let indexTotal = 0
  let minElevation = Number.POSITIVE_INFINITY
  let maxElevation = Number.NEGATIVE_INFINITY

  for (const face of faces) {
    vertexTotal += face.positions.length / 3
    indexTotal += face.indices.length
    minElevation = Math.min(minElevation, face.minElevation)
    maxElevation = Math.max(maxElevation, face.maxElevation)
  }

  const positions = new Float32Array(vertexTotal * 3)
  const colors = new Float32Array(vertexTotal * 3)
  const indices = new Uint32Array(indexTotal)
  let vertexOffset = 0
  let indexOffset = 0

  for (const face of faces) {
    positions.set(face.positions, vertexOffset * 3)
    colors.set(face.colors, vertexOffset * 3)
    for (let index = 0; index < face.indices.length; index++) {
      indices[indexOffset + index] = (face.indices[index] ?? 0) + vertexOffset
    }
    vertexOffset += face.positions.length / 3
    indexOffset += face.indices.length
  }

  const raw = new BufferGeometry()
  raw.setAttribute('position', new BufferAttribute(positions, 3))
  raw.setAttribute('color', new BufferAttribute(colors, 3))
  raw.setIndex(new BufferAttribute(indices, 1))

  // Shared-edge vertices are bit-identical across faces, so welding within a tiny tolerance is exact.
  const geometry = mergeVertices(raw, 1e-5)
  raw.dispose()
  geometry.computeVertexNormals()

  return { geometry, minElevation, maxElevation }
}
